config/routes.rb
Rails.application.routes.draw do
 root    'pages#home'
  get    'contattaci' => 'pages#contattaci'
  get    'production' => 'pages#production'
  get    'dovesiamo'  => 'pages#dovesiamo'
  get    'signup'     => 'users#new'
  get    '/login'     => 'sessions#new'
  post   'login'      => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="center">

<div id="mc_embed_signup">
<form action="https://cutdownrecords.us18.list-manage.com/subscribe/post?u=c7cc22d28a98370569fea11f4&amp;id=9cd1217219" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate center" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">  
  <input type="email" value="" name="EMAIL" class="validate center white black-text" id="mce-EMAIL" placeholder="Inserisci qui la tua email!" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c7cc22d28a98370569fea11f4_9cd1217219" tabindex="-1" value=""></div>
    <div class="clear"><button class="btn btn-lg btn-danger" type="submit" name="action" style="margin-bottom: 10px;">Voglio Registrarmi alla Newsletter!</button></div>
    </div>
</form>
</div>
<br>
<br>

          <h5>Contattaci e Seguici</h5>
          <a href="https://wa.me/393891086664" target="_blank"><i class="icon-footer fab fa-whatsapp"></i></a>
          <a href="mailto:cutdownrecords2017@gmail.com"  target="_blank"><i class="icon-footer fa fa-envelope"></i></a>
          <a href="https://m.me/Cutdownrecords?fbclid=IwAR11xCvca_lH-i67cwr6WR5kYKES7ZCUWlD9K4MjBGpPsrdwSsd65Y0VwE0"  target="_blank"><i class="icon-footer fab fa-facebook-messenger"></i></a>
          <a href="https://www.facebook.com/pg/Cutdownrecords/posts/?ref=page_internal"  target="_blank"><i class="icon-footer fab fa-facebook-square"></i></a>
          <a href="https://www.instagram.com/cutdownrecords/?hl=it" target="_blank"><i class="icon-footer fab fa-instagram"></i></a>
          <a href="https://www.youtube.com/channel/UClRNlBbbKLEqBLtA31I1goQ" target="_blank"><i class="icon-footer fab fa-youtube"></i></a>
          <br>
          <h5 style="float: left; font-size: 0.8em">2020 &copy Oigres WD</h5>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= nav_bar fixed: :top, responsive: true, brand: "Cut Down Records", style: "color: #b71c1c;" do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path, :class => "nav-link", style: "color: #b71c1c;" %>
        <%= menu_item "Contattaci", contattaci_path, :class => "nav-link", style: "color: #b71c1c;" %>
        <%= menu_item "I Nostri Lavori", production_path, :class => "nav-link", style: "color: #b71c1c;" %>
        <%= menu_item "Dove Siamo", dovesiamo_path, class: "nav-link", style: "color: #b71c1c;" %>
    <% end %>
        <%= menu_group pull: :right do %>
            <% if logged_in? %>
                <%= menu_item "Utenti", users_path, class: "nav-link", style: "color: #b71c1c;" %>
                <%= menu_divider %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" style="color: #b71c1c;" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profilo", current_user, class: "nav-link", style: "color: #b71c1c;" %></li>
              <li><%= link_to "Impostazioni", edit_user_path(current_user) , class: "nav-link", style: "color: #b71c1c;" %></li>
              <li class="divider"></li>
                <%= menu_item "Esci", logout_path, method: :delete, class: "nav-link", style: "color: #b71c1c;" %>
            <% else %>
                <%= menu_item "Accedi", login_path, class: "nav-link", style: "color: #b71c1c;" %>
            <% end %>
        <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="Hai una band o sei un solista e vuoi registrare un album o una demo? Con una sala di registrazione adeguatamente insonorizzata e regia in locale separato abbiamo strumenti che ci permettono di avere risultati professionali. Offriamo servizi di mixing e mastering con ottimi prezzi e offerte."/>
    <meta name=”keywords” content="Studio registrazione, sala registrazione, project studio, studio professionale, polanesi, sori, genova, liguria,  offerte, promozioni, registrare, gruppo, band, musicale, ottimo suono, qualità audio eccellente, mixing, mastering, recording,registrare disco,incidere album, montaggio audio, montaggio video, videoclip, riprese, presa diretta, insonorizzazione"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->

    <!-- render post Facebook -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v6.0"></script>
    <script src="https://kit.fontawesome.com/4ec30d7b7a.js" crossorigin="anonymous"></script>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji+2|Rock+Salt&display=swap" rel="stylesheet">

  </head>
  <body>
     <%= render 'layouts/header' %>
     <div class="<%= (:title) %>">
        <% flash.each do |message_type, message| %>
        <div class="container alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
          <%= yield %>
            <%= render 'layouts/footer' %>
              <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>